config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: :all
  devise_scope :user do
    get 'services/:service_identifier/users/cancel', to: 'services/users/registrations#cancel', as: :cancel_user_registration
    get 'services/:service_identifier/users/sign_up', to: 'services/users/registrations#new', as: :new_user_registration
    get 'services/:service_identifier/users/edit', to: 'services/users/registrations#edit', as: :edit_user_registration
    patch 'services/:service_identifier/users', to: 'services/users/registrations#update', as: :user_registration
    put 'services/:service_identifier/users', to: 'services/users/registrations#update'
    delete 'services/:service_identifier/users', to: 'services/users/registrations#destroy'
    post 'services/:service_identifier/users', to: 'services/users/registrations#create'

    get 'services/:service_identifier/users/confirmation/new', to: 'services/users/confirmations#new', as: :new_user_confirmation
    get 'services/:service_identifier/users/confirmation', to: 'services/users/confirmations#show'
    post 'services/:service_identifier/users/confirmation', to: 'services/users/confirmations#create', as: :user_confirmation

    get 'services/:service_identifier/users/sign_in', to: 'services/users/sessions#new', as: :new_user_session
    post 'services/:service_identifier/users/sign_in', to: 'services/users/sessions#create', as: :user_session
    delete 'services/:service_identifier/users/sign_out', to: 'services/users/sessions#destroy', as: :destroy_user_session

    get 'services/:service_identifier/users/password/new', to: 'services/users/passwords#new', as: :new_user_password
    get 'services/:service_identifier/users/password/edit', to: 'services/users/passwords#edit', as: :edit_user_password
    patch 'services/:service_identifier/users/password', to: 'services/users/passwords#update', as: :user_password
    put 'services/:service_identifier/users/password', to: 'services/users/passwords#update'
    post 'services/:service_identifier/users/password', to: 'services/users/passwords#create'
  end
  devise_for :providers, controllers: {
    sessions:      'providers/sessions',
    passwords:     'providers/passwords',
    registrations: 'providers/registrations',
    confirmations: 'providers/confirmations'
  }
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  resource :service_lp, only: %i[show]
  resource :commercial_transaction, only: %i[show]
  resource :service_term, only: %i[show]
  resource :privacy_policy, only: %i[show]
  resource :contact, only: %i[show create]

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  resource :tops, only: %i[index] do
    collection { post :pay }
    collection { post :register_credit_card }
    collection { post :change_credit_card }
    collection { post :continue_register_credit_card }
    collection { post :cancel_register_credit_card }
  end

  namespace :providers, only: [] do
    resource :profile, only: %i[show update]
    resource :unsubscribe, only: %i[create]
  end

  resources :manage_services, param: :identifier
  resources :manage_service_matchings, param: :identifier, only: [:edit, :update]
  resources :manage_service_prices, param: :identifier, only: [:edit, :update]
  resources :manage_service_admins, param: :identifier, only: [:edit, :update]
  resources :manage_service_lps, param: :identifier, only: [:edit, :update]
  resources :manage_service_uis, param: :identifier, only: [:edit, :update]
  resources :manage_service_releases, param: :identifier, only: [:edit, :update]
  resources :manage_payments, param: :identifier, only: [:index, :update]
  resources :manage_users, param: :identifier, only: [:index, :show, :destroy] do
    member { get :chat_room }
  end
  resources :manage_posts, param: :identifier, only: [:index, :edit, :update, :destroy]

  # resources :services, only: %i[show]

  resources :services, only: %i[show], param: :identifier, module: :services do

    resource :users, only: [], module: :users do
      resource :mypage, only: %i[show update]
      resource :bank, only: %i[show update]
      resource :plan, only: %i[show]
      resource :unsubscribe, only: %i[create]
      resource :payment, only: [:show] do
        collection { post :pay }
        collection { post :register_credit_card }
        collection { post :change_credit_card }
        collection { post :continue_register_credit_card }
        collection { post :cancel_register_credit_card }
        collection { post :register_plan }
        collection { post :cancel_plan }
      end
    end

    resources :posts, only: %i[index show new create destroy edit update], param: :identifier do
      collection {post :upload_image}
      collection {get :search}
      collection {post :insert_post_template}
      member {patch :change_status}
    end
    resources :chat_room, only: %i[create index show], param: :identifier do
      collection {post :upload_file}
      collection {post :download_file}
      collection {post :update_last_read_at}
    end
    resources :post_entries, only: %i[create index show update], param: :identifier
    resource :own_posts, only: %i[show]

    resource :stop_alert, only: %i[show]

    resource :service_admin, only: %i[show]
    resource :service_lp, only: %i[show]
    resource :commercial_transaction, only: %i[show]
    resource :service_term, only: %i[show]
    resource :privacy_policy, only: %i[show]
    resource :contact, only: %i[show create]
  end
end

app/controllers/manage_users_controller.rb
class ManageUsersController < ProvidersController

  def index
    if params[:service_identifier].present?
      @service = current_provider.services.find_by(identifier: params[:service_identifier])
    else
      @service = current_provider.services.first
    end
    if @service.present?
      @users = @service.users.where(unsubscribe_at: nil)

      if params[:name].present?
        @users = @users.where('name LIKE ?',"%#{params[:name]}%")
      end
      if params[:email].present?
        @users = @users.where('email LIKE ?',"%#{params[:email]}%")
      end
    end
  end

  def show
    @user = User.find_by(identifier: params[:identifier])

    @breadcrumbs = []
    @breadcrumbs.push(
      {display_text: 'ユーザー一覧', path: manage_users_path(service_identifier: @user.service.identifier)},
      {display_text: @user.name}
    )
  end

  def destroy
    @user = User.find_by(identifier: params[:identifier])
    res = @user.unsubscribe(unsubscribe_reason: params[:unsubscribe_reason])

    if res[:result]
      redirect_to manage_users_path, notice: '退会処理が完了しました。'
    else
      flash[:alert] = res[:message]
      render :index
    end
  end

  def chat_room
    @user = User.find_by(identifier: params[:identifier])
    redirect_to manage_user_path(@user.identifier), notice: 'チャットはありません。' and return if @user.chat_members.blank?

    @breadcrumbs = []
    @breadcrumbs.push(
      {display_text: 'ユーザー一覧', path: manage_users_path(service_identifier: @user.service.identifier)},
      {display_text: @user.name, path: manage_user_path(@user.identifier)},
      {display_text: 'チャット'}
    )

    chat_room_ids = @user.chat_members.pluck(:chat_room_id).uniq
    @chat_rooms = ChatRoom.includes([chat_members: :user], :chat_messages).where(id: chat_room_ids).order(updated_at: :desc)
    @chat_room = if params[:chat_room_identifier].present?
                   ChatRoom.find_by(identifier: params[:chat_room_identifier])
                 else
                   @chat_rooms.first
                 end
    @chat_messages = @chat_room.chat_messages
  end

end

app/views/manage_users/chat_room.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag 'chat/application', media: 'all'

.chat_room
  .container-fluid
    .row
      .col-md-2.border-right.p-0
        .list-group
          - @chat_rooms.each do |chat_room|
            -if chat_room.identifier == @chat_room.identifier
              .p-4.bg-info
                =chat_room.chat_members.where.not(user_id: @user.id)&.first&.user&.name
            -else
              .p-4
                = link_to chat_room_manage_user_path(identifier: @user.identifier, chat_room_identifier: chat_room.identifier), class: 'd-block' do
                  =chat_room.chat_members.where.not(user_id: @user.id)&.first&.user&.name
      .col-md-10
        .direct-chat#chat_messages{"data-chat_room_identifier": "#{@chat_room.identifier}", "data-user_id": "#{@user.id}", "data-service_identifier": "#{@user.service.identifier}"}
          .box-body.chat-messages.p-4
            -@chat_messages.each do |chat_message|
              -if chat_message.user_id == @user.id
                = render partial: 'services/chat_room/own_message', locals: {chat_message: chat_message}
              -else
                = render partial: 'services/chat_room/other_message', locals: {chat_message: chat_message}

app/views/manage_users/index.html.haml
-if current_provider.services.blank?
  =render 'layouts/parts/no_service_alert'
-else
  .container-fluid
    .row
      .col-2.p-0
        .list-group
          -current_provider.services.each do |service|
            =link_to service.name, manage_users_path(service_identifier: service.identifier), class: "list-group-item list-group-item-action text-break #{'active' if @service.identifier == service.identifier}"
      .col-10.p-0
        .box.box-solid
          .box-header
            = form_with url: manage_users_path, method: :get, local: true do |f|
              .input-group.d-flex.justify-content-end.align-items-center.py-3
                .m-0
                  %input.form-control{name: 'name', type: 'text', placeholder: 'ニックネーム', value: "#{params[:name] if params.present?}"}
                .ml-4
                  %input.form-control{name: 'email', type: 'text', placeholder: 'メールアドレス', value: "#{params[:email] if params.present?}"}
                .ml-2
                  = f.button :submit, class: 'btn btn-info' do
                    %i.fa.fa-search
              =f.hidden_field :service_identifier, value: params[:service_identifier]
          .box-body.table-responsive.no-padding
            %table.table.no-margin.table-hover
              %thead
                %tr
                  %th アイコン
                  %th ID
                  %th ニックネーム
                  %th メールアドレス
              %tbody
                -if @users.present?
                  -@users.each do |user|
                    %tr.cursor-pointer{onclick: "window.location='#{manage_user_path(user.identifier)}'", role: 'link'}
                      %td.w-100px
                        .border-radius-50-per.overflow-hidden.border.d-flex.align-items-center.justify-content-center.w-100px.h-100px
                          -if user.profile_image.present?
                            = image_tag user.profile_image.url, {class: 'w-100', alt: 'User Image'}
                          -else
                            = image_tag 'no_image.png', {class: 'w-100', alt: 'User Image'}
                      %td
                        =user.identifier
                      %td
                        =user.name
                      %td
                        =user.email

app/views/manage_users/show.html.haml
.d-flex.justify-content-between.align-items-center.m-4
  .m-0
    =link_to 'チャット', chat_room_manage_user_path(identifier: @user.identifier), class: 'btn btn-info'
  .m-0
    =link_to '強制退会', manage_user_path(@user.identifier), method: :delete, data: {confirm: '強制退会させますか？'}, class: 'btn btn-danger'

.box.box-solid
  .box-header.with-border
    %h3.box-title 基本情報
  .box-body
    %dl
      %dt= User.human_attribute_name(:profile_image)
      %dd
        .border-radius-50-per.overflow-hidden.border.d-flex.align-items-center.justify-content-center.w-200px.h-200px
          -if @user.profile_image.present?
            = image_tag @user.profile_image.url, {class: 'w-100', alt: 'User Image'}
          -else
            = image_tag 'no_image.png', {class: 'w-100', alt: 'User Image'}
      %dt= User.human_attribute_name(:name)
      %dd= @user.name
      %dt= User.human_attribute_name(:email)
      %dd= @user.email

.box.box-solid
  .box-header.with-border
    %h3.box-title 口座情報
  .box-body
    %dl
      %dt= User.human_attribute_name(:bank_name)
      %dd= @user.bank_name
      %dt= User.human_attribute_name(:bank_code)
      %dd= @user.bank_code
      %dt= User.human_attribute_name(:bank_branch_name)
      %dd= @user.bank_branch_name
      %dt= User.human_attribute_name(:bank_branch_number)
      %dd= @user.bank_branch_number
      %dt= User.human_attribute_name(:bank_account_type)
      %dd= @user.bank_account_type
      %dt= User.human_attribute_name(:bank_account_number)
      %dd= @user.bank_account_number
      %dt= User.human_attribute_name(:bank_account_holder)
      %dd= @user.bank_account_holder

.box.box-solid
  .box-header.with-border
    %h3.box-title クレジットカード・プラン情報
  .box-body
    %dl
      %dt= User.human_attribute_name(:pay_jp_customer_id)
      %dd= @user.pay_jp_customer_id
      %dt= User.human_attribute_name(:pay_jp_subscription_id)
      %dd= @user.pay_jp_subscription_id
      %dt= User.human_attribute_name(:pay_jp_fingerprint)
      %dd= @user.pay_jp_fingerprint