config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: :all
  devise_scope :user do
    get 'services/:service_identifier/users/cancel', to: 'services/users/registrations#cancel', as: :cancel_user_registration
    get 'services/:service_identifier/users/sign_up', to: 'services/users/registrations#new', as: :new_user_registration
    get 'services/:service_identifier/users/edit', to: 'services/users/registrations#edit', as: :edit_user_registration
    patch 'services/:service_identifier/users', to: 'services/users/registrations#update', as: :user_registration
    put 'services/:service_identifier/users', to: 'services/users/registrations#update'
    delete 'services/:service_identifier/users', to: 'services/users/registrations#destroy'
    post 'services/:service_identifier/users', to: 'services/users/registrations#create'

    get 'services/:service_identifier/users/confirmation/new', to: 'services/users/confirmations#new', as: :new_user_confirmation
    get 'services/:service_identifier/users/confirmation', to: 'services/users/confirmations#show'
    post 'services/:service_identifier/users/confirmation', to: 'services/users/confirmations#create', as: :user_confirmation

    get 'services/:service_identifier/users/sign_in', to: 'services/users/sessions#new', as: :new_user_session
    post 'services/:service_identifier/users/sign_in', to: 'services/users/sessions#create', as: :user_session
    delete 'services/:service_identifier/users/sign_out', to: 'services/users/sessions#destroy', as: :destroy_user_session

    get 'services/:service_identifier/users/password/new', to: 'services/users/passwords#new', as: :new_user_password
    get 'services/:service_identifier/users/password/edit', to: 'services/users/passwords#edit', as: :edit_user_password
    patch 'services/:service_identifier/users/password', to: 'services/users/passwords#update', as: :user_password
    put 'services/:service_identifier/users/password', to: 'services/users/passwords#update'
    post 'services/:service_identifier/users/password', to: 'services/users/passwords#create'
  end
  devise_for :providers, controllers: {
    sessions:      'providers/sessions',
    passwords:     'providers/passwords',
    registrations: 'providers/registrations',
    confirmations: 'providers/confirmations'
  }
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  resource :service_lp, only: %i[show]
  resource :commercial_transaction, only: %i[show]
  resource :service_term, only: %i[show]
  resource :privacy_policy, only: %i[show]
  resource :contact, only: %i[show create]

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  resource :tops, only: %i[index] do
    collection { post :pay }
    collection { post :register_credit_card }
    collection { post :change_credit_card }
    collection { post :continue_register_credit_card }
    collection { post :cancel_register_credit_card }
  end

  namespace :providers, only: [] do
    resource :profile, only: %i[show update]
    resource :unsubscribe, only: %i[create]
  end

  resources :manage_services, param: :identifier
  resources :manage_service_matchings, param: :identifier, only: [:edit, :update]
  resources :manage_service_prices, param: :identifier, only: [:edit, :update]
  resources :manage_service_admins, param: :identifier, only: [:edit, :update]
  resources :manage_service_lps, param: :identifier, only: [:edit, :update]
  resources :manage_service_uis, param: :identifier, only: [:edit, :update]
  resources :manage_service_releases, param: :identifier, only: [:edit, :update]
  resources :manage_payments, param: :identifier, only: [:index, :update]
  resources :manage_users, param: :identifier, only: [:index, :show, :destroy] do
    member { get :chat_room }
  end
  resources :manage_posts, param: :identifier, only: [:index, :edit, :update, :destroy]

  # resources :services, only: %i[show]

  resources :services, only: %i[show], param: :identifier, module: :services do

    resource :users, only: [], module: :users do
      resource :mypage, only: %i[show update]
      resource :bank, only: %i[show update]
      resource :plan, only: %i[show]
      resource :unsubscribe, only: %i[create]
      resource :payment, only: [:show] do
        collection { post :pay }
        collection { post :register_credit_card }
        collection { post :change_credit_card }
        collection { post :continue_register_credit_card }
        collection { post :cancel_register_credit_card }
        collection { post :register_plan }
        collection { post :cancel_plan }
      end
    end

    resources :posts, only: %i[index show new create destroy edit update], param: :identifier do
      collection {post :upload_image}
      collection {get :search}
      collection {post :insert_post_template}
      member {patch :change_status}
    end
    resources :chat_room, only: %i[create index show], param: :identifier do
      collection {post :upload_file}
      collection {post :download_file}
      collection {post :update_last_read_at}
    end
    resources :post_entries, only: %i[create index show update], param: :identifier
    resource :own_posts, only: %i[show]

    resource :stop_alert, only: %i[show]

    resource :service_admin, only: %i[show]
    resource :service_lp, only: %i[show]
    resource :commercial_transaction, only: %i[show]
    resource :service_term, only: %i[show]
    resource :privacy_policy, only: %i[show]
    resource :contact, only: %i[show create]
  end
end

app/controllers/manage_payments_controller.rb
class ManagePaymentsController < ProvidersController
  def index
    if params[:service_identifier].present?
      @service = current_provider.services.find_by(identifier: params[:service_identifier])
    else
      @service = current_provider.services.first
    end

    if @service.present?
      @post_entries = @service.post_entries.where(status: [:paid, :deposited]).order(updated_at: :desc)

      if params[:from_date].present?
        @post_entries = @post_entries.where('entry_at >= ?', params[:from_date])
      end
      if params[:to_date].present?
        @post_entries = @post_entries.where('entry_at <= ?', params[:to_date])
      end
      if params[:status].present?
        @post_entries = @post_entries.where('status = ?', params[:status])
      end
    end
  end

  def update
    post_entry = PostEntry.find_by(identifier: params[:identifier])
    if post_entry.present? && params[:status].present?
      post_entry.update(
        status: params[:status].to_i,
        deposited_price: (post_entry.price * (1 - post_entry.transaction_payment_margin*0.01)).to_i
      )
      redirect_to manage_payments_path(service_identifier: post_entry.service.identifier), notice: '更新しました。'
    else
      flash[:alert] = '更新に失敗しました'
      render :index
    end
  end
end

app/views/manage_payments/index.html.haml
-if current_provider.services.blank?
  =render 'layouts/parts/no_service_alert'
-else
  .container-fluid
    .row
      .col-2.p-0
        .list-group
          -current_provider.services.each do |service|
            =link_to manage_payments_path(service_identifier: service.identifier), class: "list-group-item list-group-item-action text-break #{'active' if @service.identifier == service.identifier}" do
              =service.name
              - payment_count = service.post_entries.paid.count
              -if payment_count > 0
                %span.badge.alert-danger.m-0.text-center= payment_count
      .col-10.p-0
        .box.box-solid
          .box-header
            = form_with url: manage_payments_path, method: :get, local: true do |f|
              .input-group.d-flex.justify-content-end.align-items-center.py-3
                .mb-0
                  応募アクション日：
                .ml-2
                  %input.form-control{name: 'from_date', type: 'date', value: "#{params[:from_date] if params.present?}"}
                .ml-2
                  〜
                .ml-2
                  %input.form-control{name: 'to_date', type: 'date', value: "#{params[:to_date] if params.present?}"}
                .ml-4
                  = f.select :status, [['未入金', PostEntry.statuses[:paid]], ['入金済', PostEntry.statuses[:deposited]]], {include_blank: 'すべて', selected: params[:status]}, {class: 'form-control'}
                .ml-2
                  = f.button :submit, class: 'btn btn-info' do
                    %i.fa.fa-search
              =f.hidden_field :service_identifier, value: params[:service_identifier]
          .box-body.table-responsive.no-padding
            %table.table.no-margin
              %thead
                %tr
                  %th ユーザーID
                  %th ニックネーム
                  %th メールアドレス
                  %th 支払金額（税込）
                  %th 支払先
                  %th ステータス
                  %th 応募アクション日
                  %th 募集アクション
              %tbody
                -if @post_entries.present?
                  -@post_entries.each do |post_entry|
                    %tr
                      %td
                        -if post_entry.service.paid_by_post_user?
                          =post_entry.user.identifier
                        -if post_entry.service.paid_by_apply_user?
                          =post_entry.post.user.identifier
                      %td
                        -if post_entry.service.paid_by_post_user?
                          =post_entry.user.name
                        -if post_entry.service.paid_by_apply_user?
                          =post_entry.post.user.name
                      %td
                        -if post_entry.service.paid_by_post_user?
                          =post_entry.user.email
                        -if post_entry.service.paid_by_apply_user?
                          =post_entry.post.user.email
                      %td
                        .mb-2
                          ="#{(post_entry.price * (1 - post_entry.transaction_payment_margin*0.01)).to_i.to_s(:delimited)} 円"
                        .text-muted
                          = "取引金額：#{post_entry.price.to_s(:delimited)} 円"
                        .text-muted
                          = "手数料率：#{post_entry.transaction_payment_margin} %"
                      %td
                        .mb-2
                          %label= User.human_attribute_name(:bank_code)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_name
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_name
                        .mb-2
                          %label= User.human_attribute_name(:bank_code)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_code
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_code
                        .mb-2
                          %label= User.human_attribute_name(:bank_branch_name)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_branch_name
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_branch_name
                        .mb-2
                          %label= User.human_attribute_name(:bank_branch_number)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_branch_number
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_branch_number
                        .mb-2
                          %label= User.human_attribute_name(:bank_account_type)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_account_type
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_account_type
                        .mb-2
                          %label= User.human_attribute_name(:bank_account_number)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_account_number
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_account_number
                        .mb-2
                          %label= User.human_attribute_name(:bank_account_holder)
                          -if post_entry.service.paid_by_post_user?
                            =post_entry.user.bank_account_holder
                          -if post_entry.service.paid_by_apply_user?
                            =post_entry.post.user.bank_account_holder
                      %td
                        -if post_entry.deposited?
                          入金済
                        -elsif post_entry.paid?
                          未入金
                      %td
                        =post_entry.entry_at.strftime('%Y/%m/%d %H:%M')
                      %td
                        = link_to(service_post_path(service_identifier: post_entry.post.service.identifier, identifier: post_entry.post.identifier), class: '') do
                          = post_entry.post.title
                      %td
                        =form_with url: manage_payment_path(post_entry.identifier), method: :patch, local: true do |f|
                          -if post_entry.paid?
                            = f.hidden_field :status, value: PostEntry.statuses[:deposited]
                            = f.submit '入金済にする', data: {confirm: '入金済みにしてもよろしいですか？'}, class: 'btn btn-success'
                          -if post_entry.deposited?
                            = f.hidden_field :status, value: PostEntry.statuses[:paid]
                            = f.submit '未入金にする', data: {confirm: '未入金にしてもよろしいですか？'}, class: 'btn btn-warning'