config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: :all
  devise_scope :user do
    get 'services/:service_identifier/users/cancel', to: 'services/users/registrations#cancel', as: :cancel_user_registration
    get 'services/:service_identifier/users/sign_up', to: 'services/users/registrations#new', as: :new_user_registration
    get 'services/:service_identifier/users/edit', to: 'services/users/registrations#edit', as: :edit_user_registration
    patch 'services/:service_identifier/users', to: 'services/users/registrations#update', as: :user_registration
    put 'services/:service_identifier/users', to: 'services/users/registrations#update'
    delete 'services/:service_identifier/users', to: 'services/users/registrations#destroy'
    post 'services/:service_identifier/users', to: 'services/users/registrations#create'

    get 'services/:service_identifier/users/confirmation/new', to: 'services/users/confirmations#new', as: :new_user_confirmation
    get 'services/:service_identifier/users/confirmation', to: 'services/users/confirmations#show'
    post 'services/:service_identifier/users/confirmation', to: 'services/users/confirmations#create', as: :user_confirmation

    get 'services/:service_identifier/users/sign_in', to: 'services/users/sessions#new', as: :new_user_session
    post 'services/:service_identifier/users/sign_in', to: 'services/users/sessions#create', as: :user_session
    delete 'services/:service_identifier/users/sign_out', to: 'services/users/sessions#destroy', as: :destroy_user_session

    get 'services/:service_identifier/users/password/new', to: 'services/users/passwords#new', as: :new_user_password
    get 'services/:service_identifier/users/password/edit', to: 'services/users/passwords#edit', as: :edit_user_password
    patch 'services/:service_identifier/users/password', to: 'services/users/passwords#update', as: :user_password
    put 'services/:service_identifier/users/password', to: 'services/users/passwords#update'
    post 'services/:service_identifier/users/password', to: 'services/users/passwords#create'
  end
  devise_for :providers, controllers: {
    sessions:      'providers/sessions',
    passwords:     'providers/passwords',
    registrations: 'providers/registrations',
    confirmations: 'providers/confirmations'
  }
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  resource :service_lp, only: %i[show]
  resource :commercial_transaction, only: %i[show]
  resource :service_term, only: %i[show]
  resource :privacy_policy, only: %i[show]
  resource :contact, only: %i[show create]

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  resource :tops, only: %i[index] do
    collection { post :pay }
    collection { post :register_credit_card }
    collection { post :change_credit_card }
    collection { post :continue_register_credit_card }
    collection { post :cancel_register_credit_card }
  end

  namespace :providers, only: [] do
    resource :profile, only: %i[show update]
    resource :unsubscribe, only: %i[create]
  end

  resources :manage_services, param: :identifier
  resources :manage_service_matchings, param: :identifier, only: [:edit, :update]
  resources :manage_service_prices, param: :identifier, only: [:edit, :update]
  resources :manage_service_admins, param: :identifier, only: [:edit, :update]
  resources :manage_service_lps, param: :identifier, only: [:edit, :update]
  resources :manage_service_uis, param: :identifier, only: [:edit, :update]
  resources :manage_service_releases, param: :identifier, only: [:edit, :update]
  resources :manage_payments, param: :identifier, only: [:index, :update]
  resources :manage_users, param: :identifier, only: [:index, :show, :destroy] do
    member { get :chat_room }
  end
  resources :manage_posts, param: :identifier, only: [:index, :edit, :update, :destroy]

  # resources :services, only: %i[show]

  resources :services, only: %i[show], param: :identifier, module: :services do

    resource :users, only: [], module: :users do
      resource :mypage, only: %i[show update]
      resource :bank, only: %i[show update]
      resource :plan, only: %i[show]
      resource :unsubscribe, only: %i[create]
      resource :payment, only: [:show] do
        collection { post :pay }
        collection { post :register_credit_card }
        collection { post :change_credit_card }
        collection { post :continue_register_credit_card }
        collection { post :cancel_register_credit_card }
        collection { post :register_plan }
        collection { post :cancel_plan }
      end
    end

    resources :posts, only: %i[index show new create destroy edit update], param: :identifier do
      collection {post :upload_image}
      collection {get :search}
      collection {post :insert_post_template}
      member {patch :change_status}
    end
    resources :chat_room, only: %i[create index show], param: :identifier do
      collection {post :upload_file}
      collection {post :download_file}
      collection {post :update_last_read_at}
    end
    resources :post_entries, only: %i[create index show update], param: :identifier
    resource :own_posts, only: %i[show]

    resource :stop_alert, only: %i[show]

    resource :service_admin, only: %i[show]
    resource :service_lp, only: %i[show]
    resource :commercial_transaction, only: %i[show]
    resource :service_term, only: %i[show]
    resource :privacy_policy, only: %i[show]
    resource :contact, only: %i[show create]
  end
end

app/controllers/service_lps_controller.rb
class ServiceLpsController < ApplicationController
  layout 'service_lps/layouts/application'

  def show
  end
end

app/controllers/services/service_lps_controller.rb
class Services::ServiceLpsController < ApplicationController
  def show
    redirect_to service_path(@service.identifier) unless @service.lp_enable
  end
end

app/views/service_lps/show.html.haml
#main.main.app.form
  .hero-section
    .container.nopadding
      .col-md-7
        = image_tag '10876_color.png', class: 'img-responsive w-75p', 'data-wow-delay' => '0.1s'
      .col-md-5
        .hero-content.text-center
          %h2.wow.fadeInUp{"data-wow-delay" => "0.1s"}マッチングサービスを
          %h2.wow.fadeInUp{"data-wow-delay" => "0.1s"}最短1日で作成
          %h1.wow.fadeInUp{"data-wow-delay" => "0.2s"}マッチングベース
          = link_to logged_in? ? root_path : new_provider_registration_path, class: 'btn btn-action btn-lg wow mb-5 fadeInUp', 'data-wow-delay' => '0.2s', onclick: 'gtag_report_conversion_link_sign_up(undefined)' do
            %i.fa.fa-hand-o-right
            30日間無料で使ってみる
#what-is.pitch.text-center
  .container
    .pitch-intro
      %h1.wow.fadeInUp{"data-wow-delay" => "0.1s"} マッチングベースとは？
      %p.wow.fadeInUp{"data-wow-delay" => "0.1s"}
        マッチングベースはノーコードで
        %span.emphasis<> 最短1日
        でマッチングサービスを作成できるサービスです。
      %p.wow.fadeInUp{"data-wow-delay" => "0.1s"}
        通常、マッチングサービスを構築しリリースするには最短でも1ヶ月、
        %br<>
        長ければ半年以上かかることもあります。
        %br<>
        このため、せっかく時間と費用をかけてリリースしたのに反応がイマイチなことや、リリースまでに競合サービスが出てきたため断念することなどが度々起こってしまいます。
        %br<>
        %br<>
        マッチングベースを利用することで、マッチングサービスを最短1日でリリースできるため、アイデアをすぐに形にすることができます。
        %br<>
        必要な費用はサービスの月額利用料だけで、開発費はかかりません。
        %br<>
        %br<>
        アイデアをすぐにリリースして、世の中の反応を見てみましょう！
#function.pitch.text-center
  .container
    .pitch-intro
      %h1.wow.fadeInUp{"data-wow-delay" => "0.1s"} 機能の紹介
      %p.wow.fadeInUp{"data-wow-delay" => "0.1s"}
        マッチングサービスに必要な機能を取り揃えています。
    .row
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.fas.fa-thumbs-up
        .pitch-content
          %h1
            1.ノーコード
          %p
            マッチングベースを使えば、完全ノーコードでマッチングサービスを作成することができます。
            %br<>
            画面の説明に従って設定するだけで、あなたのマッチングサービスをリリースできます。
        = image_tag '17015_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.fa.fa-credit-card
        .pitch-content
          %h1
            2.決済機能
          %p
            あなたのマッチングサービスに月額利用料を設定したり、利用ユーザー同士がお互いに支払いできる設定が可能です。
            %br<>
            ユーザー同士の支払いには、あなたへの手数料を設定することも可能です。
        = image_tag '1308_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
    .row.mt-6
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.far.fa-comments
        .pitch-content
          %h1 3.チャット機能
          %p
            あなたのマッチングサービスに登録したユーザー同士は、お互いにチャットすることができます。
            %br<>
            文章だけではなく、画像やPDFなどのファイルを送ることも可能です。
        = image_tag '16786_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.fas.fa-chart-bar
        .pitch-content
          %h1 4.Googleアナリティクス対応
          %p
            Googleアナリティクスのタグを設定することで、Googleアナリティクスでユーザー数などを確認することが可能です。
        = image_tag '9759_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
    .row.mt-6
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.far.fa-image
        .pitch-content
          %h1 5.LP設定
          %p
            あなたのマッチングサービスを紹介するLP（ランディングページ）を作成することができます。
        = image_tag '2422_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.fas.fa-info
        .pitch-content
          %h1 6.お問い合わせ機能
          %p
            あなたのマッチングサービスのユーザーからお問い合わせを受ける機能も搭載されています。
        = image_tag '11213_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
    .row.mt-6
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.fas.fa-child
        .pitch-content
          %h1 7.サーバレス
          %p
            マッチングベースはノーコードであり、サーバレス（サーバー費用不要）です。
            %br<>
            通常ランニングコストとして必要なサーバー費用はかかりません。
        = image_tag '10885_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-50p'
      .col-md-6.wow.fadeInUp.pb-5{"data-wow-delay" => "0.1s"}
        .pitch-icon
          %i.fas.fa-caret-right
        .pitch-content
          %h1 8.独自ドメインの設定
          %p.text-center
            現在準備中...
          = image_tag '16780_color.png', class: 'img-responsive drop-shadow max-w-400 m-0-auto w-30p'
    .row.mt-6
      .col-md-12
        = link_to logged_in? ? root_path : new_provider_registration_path, class: 'btn btn-action btn-lg wow fadeInUp mb-2', 'data-wow-delay' => '0.1s', onclick: 'gtag_report_conversion_link_sign_up(undefined)' do
          %i.fa.fa-hand-o-right
          30日間無料で使ってみる
.feature-sub
  .container
    .sub-inner
      %h3.wow
        今なら
        %span.emphasis<> 30日間無料
        でご利用いただけます。
        %br<>
        もちろん30日以内に退会すれば費用は一切かかりません。
      = link_to logged_in? ? root_path : new_provider_registration_path, class: 'btn btn-action btn-block btn-lg wow fadeInUp mt-2 mb-4 w-100p', 'data-wow-delay' => '0.1s', onclick: 'gtag_report_conversion_link_sign_up(undefined)' do
        %i.fa.fa-hand-o-right
        30日間無料で使ってみる
      %h4.wow 退会方法も簡単！「マイページ ＞ 退会する」からいつでも可能です。
      = image_tag 'unsubscribe.png', class: 'img-responsive max-w-800 drop-shadow m-0-auto w-100p'
#pricing.pricing-section.text-center
  .container
    .col-md-12.col-sm-12.nopadding
      .pricing-intro
        %h1.wow.fadeInUp{"data-wow-delay" => "0.1s"} 価格について
        %p.wow.fadeInUp{"data-wow-delay" => "0.1s"}
          通常マッチングサービスを運営するには、サーバー費用や開発費用などの初期投資で数十〜数百万円以上、
          %br<>
          ランニングコストで数万〜数十万円が必要です。
          %br<>
          マッチングサービスは、
          %span.emphasis<> 初期費用無料、月額19,800円（税込）
          でご利用いただけます。
        .table-right.table-center.wow.fadeInUp{"data-wow-delay" => "0.1s"}
          .icon
            %i.fa.fa-credit-card
          .pricing-details
            %h2
              %span 月額
              %span{class: 'emphasis'}<> 19,800
              %span 円
              %span.font-size-16 (税込)
              %p.font-size-22.mt-2.mb-0
            .price-image
              .price-image_content
                .price-image_first-text
                  利用開始（無料）
                .price-image_content-item.price-image_first-item
                  30日間の無料期間
                .price-image_emphasis-text
                  この日までに退会すれば完全無料
                .price-image_last-text
                  30日目
                .price-image_content-item.price-image_last-item
                  月額19,800円
            %ul
              %li 上記月額以外に費用が発生することはありませんのでご安心ください。
            = link_to logged_in? ? root_path : new_provider_registration_path, class: 'btn btn-action btn-lg wow fadeInUp w-100p', 'data-wow-delay' => '0.1s', onclick: 'gtag_report_conversion_link_sign_up(undefined)' do
              %i.fa.fa-hand-o-right
              30日間無料で使ってみる